In [2]:
from numpy import random

x = random.randint(100)

print(x)

68


In [3]:
#Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)


0.21555308500156745


In [4]:
x=random.randint(100, size=(5))

print(x)


[73 91 82 57 48]


In [5]:
x = random.randint(100, size=(3, 5))

print(x)

[[16 87  6 44 89]
 [88 64 82 53 40]
 [40 69 83 73 97]]


In [6]:
x = random.rand(5)

print(x)

[0.03195922 0.18609116 0.70431843 0.73733946 0.09183576]


In [7]:
x = random.rand(3, 5)

print(x)

[[0.63239564 0.99595711 0.57666317 0.82163868 0.9243241 ]
 [0.5848898  0.14937832 0.48931335 0.4486081  0.70543192]
 [0.3853644  0.19159095 0.48646994 0.59777605 0.41585945]]


In [8]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [9]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 7 9 3]
 [5 5 3 3 9]
 [7 7 9 9 5]]


In [10]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 7 7 5 7 5 5 3 7 5 5 3 7 7 5 5 7 7 7 7 5 7 7 7 5 7 7 7 7 7 3 3 5 5 3
 7 7 5 5 7 7 5 7 7 7 5 7 5 7 5 7 7 5 7 7 7 7 7 7 5 7 7 7 7 5 5 5 5 7 7 7 5
 7 5 7 3 5 5 5 7 7 5 3 5 7 7 7 7 5 5 3 5 5 7 5 7 7 7]


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 4 3 1 5]


In [13]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[5 3 4 2 1]
