In [6]:
#Basic
#3. Write a NumPy program to test whether none of the elements of a given array are zero. 

import numpy as np

arr=np.array([1, 2, 0, 1, 5])

if 0 in arr:
    print("A zero element found.")
else: 
    print("No zero element found.")

if all(arr):
    print("No zero element found.")
else: 
    print("A zero element found.")


A zero element found.
A zero element found.


In [11]:
#13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

arr=np.zeros(10, dtype='i')
print(arr)

arr=np.ones(10, dtype='i')
print(arr)

arr=np.ones(10, dtype='i')*5
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [12]:
#14. Write a NumPy program to create an array of integers from 30 to 70.

arr=np.arange(30,71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [13]:
#15.Write a NumPy program to create an array of all even integers from 30 to 70.

arr=np.arange(30,71,2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [23]:
#17. Write a NumPy program to generate a random number between 0 and 1.

import random as r

a=r.random()
a

0.6969211342800223

In [26]:
#18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

a=np.random.normal(0, 1, 15)
a

array([ 0.225226  ,  0.04058345,  0.6237929 , -0.65920945, -1.14042019,
       -0.9086903 , -0.25281726, -0.46292231, -0.37777818, -0.24480998,
       -1.92131499, -0.10813339,  2.31108644, -0.90152718,  0.65838983])

In [29]:
#19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

arr=np.arange(15, 55)
print(arr)
print(arr[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [38]:
#20. Write a NumPy program to create a 3X4 array and iterate over it.

a = np.arange(0,12).reshape((3, 4))
print(a)


for i in np.nditer(a):
    print(i, end=" ")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11 

In [42]:
#22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

arr=np.arange(0,21)
print(arr)

arr[(arr>=9)&(arr<=15)]*=-1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [44]:
#23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

arr=np.random.randint(0, 10, 5)
arr

array([1, 3, 1, 6, 4])

In [ ]:
"""
NumPy Array Object tasks
"""

In [45]:
#2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
#Expected Output:
#Original List: [12.23, 13.32, 100, 36.32]
#One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

mylist=[12.23, 13.32, 100, 36.32]
arr=np.array(mylist)
arr

array([ 12.23,  13.32, 100.  ,  36.32])

In [47]:
#3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
#Expected Output:
#[[ 2 3 4]
#[ 5 6 7]
#[ 8 9 10]]

arr=np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [50]:
#4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
#[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#Update sixth value to 11
#[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

arr=np.zeros(10)
print(arr)

arr[6]=11
arr

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [53]:
#6. Write a NumPy program to reverse an array (the first element becomes the last).
#Original array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
#Reverse array:
#[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

arr=np.arange(12,38)
print(arr)

arr=arr[::-1]
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [55]:
#7. Write a NumPy program to convert an array to a floating type.
#Sample output:
#Original array
#[1, 2, 3, 4]
#Array converted to a float type:
#[ 1. 2. 3. 4.]

arr=np.array([1,2,3,4])
arr=np.asfarray(arr)
print(arr)

[1. 2. 3. 4.]


In [57]:
#11. Write a NumPy program to convert a list and tuple into arrays.
#List to array:
#[1 2 3 4 5 6 7 8]
#Tuple to array:
#[[8 4 6]
#[1 2 3]]

mylist = [1, 2, 3, 4, 5, 6, 7, 8]
print("List: ")
print(np.asarray(mylist))
mytuple = ([8, 4, 6], [1, 2, 3])
print("Tuple: ")
print(np.asarray(mytuple))

List: 
[1 2 3 4 5 6 7 8]
Tuple: 
[[8 4 6]
 [1 2 3]]


In [58]:
#12. Write a NumPy program to append values to the end of an array.
#Expected Output:
#Original array:
#[10, 20, 30]
#After append values to the end of the array:
#[10 20 30 40 50 60 70 80 90]

arr=np.array([10, 20, 30])
arr=np.append(arr, [40,50,60,70,80,90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
#13. Write a NumPy program to create an empty and full array.
#Expected Output:
#[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
#[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
#[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]
#[[6 6 6]
#[6 6 6]
#[6 6 6]]

arr=np.empty((3,4))
print(arr)

arr=np.full((3,3), 6)
print(arr)

[[6.22176287e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.06099790e-312 2.90304592e+180 1.50128041e-076 1.49114259e+161]
 [4.76533936e-038 5.49607877e+170 1.37104047e-071 2.23254661e-052]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [64]:
#17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
#Expected Output:
#Array1: [ 0 10 20 40 60]
#Array2: [0, 40]
#Compare each element of array1 and array2
#[ True False False True False]

arr1=np.array([0,10,20,40,60])
arr2=np.array([0,40])

print(np.in1d(arr1, arr2))

[ True False False  True False]


In [65]:
#18. Write a NumPy program to find common values between two arrays.
#Expected Output:
#Array1: [ 0 10 20 40 60]
#Array2: [10, 30, 40]
#Common values between two arrays:
#[10 40]

arr1=np.array([0,10,20,40,60])
arr2=np.array([10,30,40])

print(np.intersect1d(arr1, arr2))

[10 40]


In [67]:
#19. Write a NumPy program to get the unique elements of an array.
#Expected Output:
#Original array:
#[10 10 20 20 30 30]
#Unique elements of the above array:
#[10 20 30]
#Original array:
#[[1 1]
#[2 3]]
#Unique elements of the above array:
#[1 2 3]

arr = np.array([10, 10, 20, 20, 30, 30])
print(arr)

print(np.unique(arr))

arr = np.array([[1, 1], [2, 3]])
print(arr)

print(np.unique(arr))


[10 10 20 20 30 30]
[10 20 30]
[[1 1]
 [2 3]]
[1 2 3]


In [ ]:
"""
NumPy Linear Algebra
"""

In [68]:
#1. Write a NumPy program to compute the multiplication of two given matrixes.

m1 = [[1, 0], [0, 1]]
m2 = [[1, 2], [3, 4]]

print(m1)
print(m2)

res = np.dot(m1, m2)
print(res)

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [ ]:
"""
NumPy: Random
"""

In [69]:
#1. Write a NumPy program to generate five random numbers from the normal distribution.
#Expected Output:
#[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]

arr=np.random.normal(0,1,5)
arr

array([-0.67592339, -0.69505165, -0.91702211,  0.69970336, -0.92074815])

In [70]:
#2. Write a NumPy program to generate six random integers between 10 and 30.
#Expected Output:
#[20 28 27 17 28 29]

arr=np.random.randint(10,30, 6)
arr

array([12, 22, 20, 11, 29, 25])

In [71]:
#3. Write a NumPy program to create a 3x3x3 array with random values.
#Expected Output:
#[[[ 0.48941799 0.58722213 0.43453926]
#[ 0.94497547 0.81081709 0.1510409 ]
#[ 0.66657127 0.29494755 0.48047144]]
#[[ 0.02287253 0.95232614 0.32264936]
#[ 0.67009741 0.25458304 0.16290913]
#[ 0.15520198 0.86826529 0.9679322 ]]
#[[ 0.13503103 0.02042211 0.24683897]
#[ 0.97852158 0.22374748 0.10798856]
#[ 0.62032646 0.5893892 0.16958144]]]

arr=np.random.normal(0,1,27).reshape(3,3,3)
arr

array([[[ 0.65745659, -0.41967052, -0.04401603],
        [-0.41141543, -0.98622045, -0.64857424],
        [ 1.21573801,  0.96723508, -0.60495857]],

       [[-0.81080114,  0.58999448,  0.5955586 ],
        [ 0.60651281,  0.84598123, -1.79737152],
        [-0.60019677, -0.77865581, -1.44202583]],

       [[ 0.64617108,  1.68890127, -0.86638922],
        [ 0.00932375, -2.02030616,  0.20966016],
        [-0.48608252, -1.01263059,  0.04596275]]])